config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/about' => 'welcome#about', as: 'about'
  get '/vendors/:id/followers' => 'vendors#followers', as: 'followers'
  resources :sessions, only: [:new]

  get '/login' => 'sessions#new'
  post '/login_user' => 'sessions#user_create'

  get '/login' => 'sessions#new'
  post '/login_vendor' => 'sessions#vendor_create'
  delete '/logout' => 'sessions#destroy'

  resources :vendors
  resources :deals do
    resources :purchased_items, only: [:new, :create]
  end
  resources :user
  get 'stripe', to: 'vendors#stripe_acct'

  get '/vendors/:id/text' => 'vendors#send_sms', as: 'text'
  get '/vendors/:id/email' => 'vendors#email_followers', as: 'email'
  put '/vendors/:id/follow' => 'vendors#follow', as: 'follow'
  delete '/vendors/:id/unfollow' => 'vendors#unfollow', as: 'unfollow'
  get '/vendor_session/new' => 'sessions#new_vendor_session', as: 'new_vendor_session'

  resources :charges
end

app/models/deal.rb
class Deal < ActiveRecord::Base
	belongs_to :vendor
	has_many :purchased_items
	has_many :users, through: :purchased_items
  validates :title, presence: true
  validates :description, presence: true
  validates :item_quantity, presence: true
  validates :item_price, presence: true
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :require_vendor_login, except: [:index, :show]

  def index
    @deals = Deal.where("end_time > ? AND item_quantity > ?", Time.now, 0).order(created_at: :desc)
    @user = User.new
    @vendor = Vendor.new
  end

  def new
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(deal_params)
    @deal.update_attributes(vendor_id: current_vendor.id, end_time: deal_time)
    @vendor = current_vendor
    if @deal.save
      @vendor.send_sms(@deal)
      UserMailer.email_followers(@deal).deliver_now
      redirect_to current_vendor
    else
      flash[:notice] = "all fields are required."
      redirect_to new_deal_path
    end
  end

  def edit
    @deal = Deal.find(params[:id])
  end

  def update
    deal = Deal.find(params[:id])
    deal.update_attributes(deal_params)
    deal.update_attributes(end_time: deal_time)
    redirect_to current_vendor
  end

  def show
    @deal = Deal.find(params[:id])
    @user = User.new
    @vendor = Vendor.new
  end

  def destroy
    deal = Deal.find(params[:id])
    deal.destroy
    redirect_to current_vendor
  end

  private

    def deal_params
      params.require(:deal).permit(:title, :description, :item_quantity, :item_price)
    end

    def deal_time
      Time.local(params[:deal]["end_time(1i)"].to_i, params[:deal]["end_time(2i)"].to_i, params[:deal]["end_time(3i)"].to_i, params[:deal]["end_time(4i)"].to_i, params[:deal]["end_time(5i)"].to_i)
    end

    def current_vendor
      return Vendor.find(session[:vendor_id])
    end

end

app/views/deals/_deal.html.erb
<div id="dealindexitem" class="col-md-10 col-xs-8">
  <ul class="list-unstyled">
      <li>
        <div id="dealpicture" class="col-md-2 col-xs-3">
          <% if deal.vendor.avatar.exists? %>
            <%= link_to image_tag(deal.vendor.avatar.url(:thumb), class: "img-circle", id: "dealvendorimage"), deal.vendor, class: "col-md-2" %>
            <% else %>
            <%= link_to image_tag('profile.png', size: "100x100"), deal.vendor, class: 'img-circle col-md-2' %>
          <% end %>
        </div>
        <div id="indexdealcontent" class= "col-md-7 col-xs-7">
          <div id="dealvendorname">
            <%= link_to deal.vendor.name, deal.vendor %>
          </div>
          <div id="dealtitle" >
            <%= link_to deal.title, deal %>
          </div>
          <div id="dealprice">
            <span>Price: $<%= deal.item_price %>  |  Items left: <%= deal.item_quantity %></span>
          </div>
          <div class='follower-div'>
            <span> time until expiration: <%= distance_of_time_in_words(Time.now.utc,deal.end_time) %></span>
            <p><span class="follower-count <%= index %>"><%= deal.vendor.favorite_vendors.count %></span> Followers </p>
          </div>
          <div id="dealindexfollow">
            <% if session[:user_id] %>
              <% if deal.vendor.favorite_vendors.exists?(user_id: session[:user_id]) %>
                <%= link_to "Unfollow", unfollow_path(session[:user_id], vendor_id: "#{deal.vendor.id}"), class: "unfollow-button", id: "idx#{index}", method: :delete %>
              <% else %>
                <%= link_to "Follow Vendor", follow_path(session[:user_id], vendor_id: "#{deal.vendor.id}"), class: "follow-button", id: "idx#{index}", method: :put %>
              <% end %>
            <% end %>
          </div>
        </div>
      </li>
  </ul>
</div>

app/views/deals/_edit.html.erb
<div class="" >
  <h3>Edit Deal</h3>
  <%= form_for @deal do |f| %>
    <%= f.label :title %><br/>
    <%= f.text_field :title, class: ("form-control") %><br/>
    <%= f.label :description %><br/>
    <%= f.text_area :description, cols:50, rows: 10, class: ("form-control")  %><br/>
    <%= f.label :item_quantity, size: 6 %><br/>
    <%= f.number_field :item_quantity, class: ("form-control") %><br/>
    <%= f.label :item_price %><br/>
    <%= f.number_field :item_price, size: 6, step: 0.01, class: ("form-control")  %><br/>
    <%= f.label :end_time %><br/>
    <div class="form-control">
    <span>Date: <%= f.date_select :end_time, class: ("form-control")  %></span>
    <span>Time:<%= f.time_select :end_time, ignore_date: true, :ampm => true,class: ("form-control")  %></span>
    </div>
    <br/><br/>
    <%= f.submit 'Update', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/deals/_new.html.erb
<div class="form-group col-md-4 new-deal" >
  <h3>Create New Deal</h3>
  <%= form_for @deal do |f| %>
    <%= f.label :title %><br/>
    <%= f.text_field :title, class: ("form-control") %><br/>
    <%= f.label :description %><br/>
    <%= f.text_area :description, cols:50, rows: 10, class: ("form-control")  %><br/>
    <%= f.label :item_quantity, size: 6 %><br/>
    <%= f.number_field :item_quantity, class: ("form-control") %><br/>
    <%= f.label :item_price %><br/>
    <%= f.number_field :item_price, size: 6, step: 0.01, class: ("form-control")  %><br/>
    <%= f.label :end_time %><br/>
    <div class="form-control">
    <span>Date: <%= f.date_select :end_time, class: ("form-control")  %></span>
    <span>Time:<%= f.time_select :end_time, ignore_date: true, :ampm => true,class: ("form-control")  %></span>
    </div>
    <br/><br/>
    <%= f.submit 'New Deal', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/deals/_user_deals.html.erb
<div id="dealindexitem">
  <ul class="list-unstyled">
      <li>
        <% if deal.vendor.avatar.exists? %>
          <%= link_to image_tag(deal.vendor.avatar.url(:thumb), class: "img-circle", id: "dealvendorimage"), deal.vendor, class: "img-circle col-md-2" %>
        <% end %>
        <div id="dealvendorname col-md-2">
          <%= link_to deal.vendor.name, deal.vendor %>
        </div>
        <div id="dealtitle col-md-2" >
          <%= link_to deal.title, deal %>
        </div>
        <div id="dealprice col-md-2">
          <span>Price: $<%= deal.item_price %>  |  Items left: <%= deal.item_quantity %></span>
        </div>
        <div>
          <span> time until expiration: <%= distance_of_time_in_words(Time.now.utc,deal.end_time) %></span>
          <p><span class="follower-count"><%= deal.vendor.favorite_vendors.count %></span> Followers </p>
        </div>
        <div id="dealindexfollow">
          <% if session[:user_id] %>
            <% if deal.vendor.favorite_vendors.exists?(user_id: session[:user_id]) %>
              <%= link_to "Unfollow", unfollow_path(session[:user_id], vendor_id: "#{deal.vendor.id}"), class: "unfollow-button", method: :delete %>
            <% else %>
              <%= link_to "Follow Vendor", follow_path(session[:user_id], vendor_id: "#{deal.vendor.id}"), class: "follow-button", method: :put %>
            <% end %>
          <% end %>
        </div>
      </li>
  </ul>
</div>

app/views/deals/edit.html.erb
<div class="col-md-5" >
  <h3>Create New Deal</h3>
  <%= form_for @deal do |f| %>
    <%= f.label :title %><br/>
    <%= f.text_field :title, class: ("form-control") %><br/>
    <%= f.label :description %><br/>
    <%= f.text_area :description, cols:50, rows: 10, class: ("form-control")  %><br/>
    <%= f.label :item_quantity, size: 6 %><br/>
    <%= f.number_field :item_quantity, class: ("form-control") %><br/>
    <%= f.label :item_price %><br/>
    <%= f.number_field :item_price, size: 6, step: 0.01, class: ("form-control")  %><br/>
    <%= f.label :end_time %><br/>
    <div class="form-control">
    <span>Date: <%= f.date_select :end_time, class: ("form-control")  %></span>
    <span>Time:<%= f.time_select :end_time, ignore_date: true, :ampm => true,class: ("form-control")  %></span>
    </div>
    <br/><br/>
    <%= f.submit 'New Deal', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/deals/index.html.erb
<div id="dealindexpage" class="col-md-12 col-xs-5">
  <div id="dealindexitems" class="col-md-6">
    <% @deals.each_with_index do |deal, index| %>
      <%=render partial: '/deals/deal', locals: {deal: deal, index: index} %>
    <% end %>
  </div>
  <div id="dealindexinfo" class="container col-md-6">
    <div id="dealwelcome">
      <h1 id="dealindexahoy">A'hoy!</h1>
      <h2 id="dealindexahoy">Grab a Deal!</h2>
    </div>
    <div id="importanttext">
      <h4 id="deal-index-title">Important things to consider:</h4>
      <ul>
        <li><h5>If you make a purchase leave plenty of time to pick up.</h5></li>
        <li><h5>If you cannot pick up, contact the vendor to see if they will hold the item for you.</h5></li>
        <li><h5>If you need to cancel your purchase contact the vendor.</h5></li>
        <li><h5>Buy items you are going to consume immediately.</h5></li>
        <li><h5><a href="#">Click here</a> for all terms and conditions.</h5></li>
      </ul>
    </div>

  </div>

</div>

<!-- renders modal for login (user & vendor) -->
<%= render 'welcome/vendor_login', locals: {@user => @user, @vendor => @vendor}%>
<%= render 'welcome/user_login', locals: {@user => @user, @vendor => @vendor}%>
<!-- renders modal for vendor sign up -->
<%= render 'welcome/signup_vendor', locals: {@vendor => @vendor} %>
<%= render 'user/new_user', locals: {@user => @user, @vendor => @vendor}%>

app/views/deals/new.html.erb
<div class="form-group col-md-4 new-deal" >
  <h3>Create New Deal</h3>
  <%= form_for @deal do |f| %>
    <%= f.label :title %><br/>
    <%= f.text_field :title, class: ("form-control") %><br/>
    <%= f.label :description %><br/>
    <%= f.text_area :description, cols:50, rows: 10, class: ("form-control")  %><br/>
    <%= f.label :item_quantity, size: 6 %><br/>
    <%= f.number_field :item_quantity, class: ("form-control") %><br/>
    <%= f.label :item_price %><br/>
    <%= f.number_field :item_price, size: 6, step: 0.01, class: ("form-control")  %><br/>
    <%= f.label :end_time %><br/>
    <div class="form-control">
    <span>Date: <%= f.date_select :end_time, class: ("form-control")  %></span>
    <span>Time:<%= f.time_select :end_time, ignore_date: true, :ampm => true,class: ("form-control")  %></span>
    </div>
    <br/><br/>
    <%= f.submit 'New Deal', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/deals/show.html.erb
<div id="deal-banner" class="container"></div>
<div id="deal-container" class="container">
  <div class="row">

    <div id="deal-info" class="col-md-5 text-center">
      <div id="deal-map" class="container">
        <div id="panel" class="google-map">
          <input type="hidden" id="address" type="textbox" value="<%= @deal.vendor.address %>">
        </div>
        <div id="map-canvas" style="height: 250px;"></div>
      </div>
      <h1 id="deal-welcome-user">One more click for yummy food...</h1>
    </div>

    <div class="col-md-1"></div>

    <div class="col-md-5 text-center">
      <div id="deal-vendor-info" class="container">
      <% if @deal.vendor.avatar.exists? %>
        <%= link_to image_tag(@deal.vendor.avatar.url(:thumb), class: "img-circle", id: "dealvendorimage"), @deal.vendor, class: "img-circle" %>
      <% else %>
        <%= link_to image_tag('profile.png', size:'100x100'), @deal.vendor, class: 'img-circle' %>
      <% end %>
        <h3><%= link_to @deal.vendor.name, @deal.vendor %></h3>
        <h5>Phone: <%= @deal.vendor.phone_number %></h5>
        <h5>Address: <%= @deal.vendor.address %></h5>
              <h2><%= @deal.title %></h2>
      <p><%= @deal.description%></p>
      <p>Quantity: <%= @deal.item_quantity %> | Cost Per Item: $<span id="dealprice"><%= @deal.item_price %></span>0</p>
      <p>Time Until Expiration: <%= distance_of_time_in_words(Time.now.utc,@deal.end_time) %></p><br>
      <% if current_user %>
        <%= link_to 'Purchase', new_deal_purchased_item_path(@deal.id), class: 'btn-md btn-lg btn-primary purchase-button'%>
      <% end %>
      <div id="purchase-form-area">
      </div>
      <% if current_vendors_deal?(@deal) %>
        <a href="#" data-toggle="modal" data-target="#editDeal" class="btn-sm btn-lg btn-primary">Edit</a>
        <%= link_to 'delete', deal_path(@deal.id), method: 'DELETE', class: 'btn-sm btn-lg btn-danger', data: {confirm: "Are you sure you want to delete this deal?"}  %>
      <% end %>
      </div>
    </div>

    <div class="col-md-5 text-center">
    </div>

    <div class="col-md-1"></div>

    <div class="col-md-5">
    </div>

  </div>
</div>

<div class="container">
  <div class="modal fade" id="editDeal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Edit Deal</h4>
        </div>
        <div class="modal-body">
          <%= render 'deals/edit', locals: {deal: @deal} %>
        </div>
      </div>
    </div>
  </div>
</div>



<!-- renders modal for login (user & vendor) -->
<%= render 'welcome/vendor_login', locals: {@user => @user, @vendor => @vendor}%>
<%= render 'welcome/user_login', locals: {@user => @user, @vendor => @vendor}%>
<!-- renders modal for vendor sign up -->
<%= render 'welcome/signup_vendor', locals: {@vendor => @vendor} %>
<%= render 'user/new_user', locals: {@user => @user, @vendor => @vendor}%>