config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/about' => 'welcome#about', as: 'about'
  get '/vendors/:id/followers' => 'vendors#followers', as: 'followers'
  resources :sessions, only: [:new]

  get '/login' => 'sessions#new'
  post '/login_user' => 'sessions#user_create'

  get '/login' => 'sessions#new'
  post '/login_vendor' => 'sessions#vendor_create'
  delete '/logout' => 'sessions#destroy'

  resources :vendors
  resources :deals do
    resources :purchased_items, only: [:new, :create]
  end
  resources :user
  get 'stripe', to: 'vendors#stripe_acct'

  get '/vendors/:id/text' => 'vendors#send_sms', as: 'text'
  get '/vendors/:id/email' => 'vendors#email_followers', as: 'email'
  put '/vendors/:id/follow' => 'vendors#follow', as: 'follow'
  delete '/vendors/:id/unfollow' => 'vendors#unfollow', as: 'unfollow'
  get '/vendor_session/new' => 'sessions#new_vendor_session', as: 'new_vendor_session'

  resources :charges
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

  include Messenger

	has_secure_password
	has_many :favorite_vendors
	has_many :users, through: :favorite_vendors
  has_many :followers, through: :favorite_vendors, source: :user
	has_many :deals

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates_confirmation_of :password


  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/profile.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  def self.post_back(code)
    client_id = ENV['STRIPE_CLIENT_ID']
    secret = ENV['STRIP_SECRET_KEY']
    uri = URI("https://connect.stripe.com/oauth/token?client_secret=#{secret}&code=#{code}&grant_type=authorization_code")
    res = Net::HTTP.post_form(uri, 'q' => 'ruby')
    return res
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  def index
    @vendors = Vendor.all.sort_by {|vendor| vendor.deals.count}.reverse
    @vendor = Vendor.new
    @user = User.new
  end

  def new
    @vendor = Vendor.new
    if request.xhr?
      render(partial: 'new', object: @vendor)
    end
  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      session[:vendor_id] = @vendor.id
      redirect_to vendor_path(@vendor)
    else
      flash[:error] = "There was a problem with your submission"
      redirect_to root_path
    end
  end

  def show
    @deal = Deal.new
    @vendor = Vendor.find(params[:id])
    @user = User.new
    @current_deals = @vendor.deals.where("end_time > ? AND item_quantity > ?", Time.now, 0).order(created_at: :desc)
    @last_five = @vendor.deals.limit(5)
  end

  def edit
    @vendor = Vendor.find(params[:id])
  end

  def update
    @vendor = Vendor.find(params[:id])
    @vendor.assign_attributes(vendor_params)
    if @vendor.save
      flash[:notice] = "Your account has been successfully edited"
      redirect_to vendor_path(@vendor)
    else
      render :edit
    end
  end

  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy
    session[:vendor_id] = nil
    redirect_to root_path
  end

  def send_sms
    @vendor = Vendor.find(params[:id])
    @vendor.send_followers_sms
    redirect_to vendor_path(@vendor.id)
  end

  def email_followers
    @vendor = Vendor.find(params[:id])
    @users = @vendor.users
    UserMailer.email_followers(@users.pluck(:email)).deliver
    redirect_to @vendor
  end

  def follow
    @vendor = Vendor.find(params[:vendor_id])
    @followers = @vendor.favorite_vendors
    unless @followers.exists?(user_id: params[:id])
      @vendor.favorite_vendors.create(user_id: params[:id])
      if request.xhr?
        return render :json => { :upvote => (@followers.count).to_s}
      end
    end
    return render :json => { :upvote => (@followers.count).to_s}
  end

  def unfollow
    @vendor = Vendor.find(params[:vendor_id])
    @followers = @vendor.favorite_vendors
    if @followers.exists?(user_id: params[:id])
      vote = @vendor.favorite_vendors.find_by(user_id: params[:id])
      vote.destroy
      if request.xhr?
        return render :json => { :downvote => (@followers.count).to_s}
      end
    end
    return render :json => { :downvote => (@followers.count).to_s}
  end

  # this is for index of Vendors followers
  def followers
    @vendor = Vendor.find(params[:id])
  end

  def stripe_acct
    response = Vendor.post_back(params[:code])
    response_hash = JSON.parse(response.body)
    current_vendor.update_attributes(access_token: response_hash["access_token"], livemode: response_hash["livemode"], refresh_token: response_hash["refresh_token"], token_type: response_hash["token_type"], stripe_publishable_key: response_hash["stripe_publishable_key"], stripe_user_id: response_hash["stripe_user_id"], scope: response_hash["scope"] )
    redirect_to vendor_path(current_vendor.id)
  end


  private

    def vendor_params
      params.fetch(:vendor, {}).permit(:username, :password, :email, :name, :address, :phone_number, :bio, :avatar, :password_confirmation)
    end

end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_deal_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <h4>Create New Deal</h4>
      <%= form_for @deal do |f| %>
        <%= f.label :title %><br/>
        <%= f.text_field :title, class: ("form-control") %><br/>
        <%= f.label :description %><br/>
        <%= f.text_area :description, cols:50, rows: 5, class: ("form-control")  %><br/>
        <%= f.label :item_quantity, size: 6 %><br/>
        <%= f.number_field :item_quantity, class: ("form-control") %><br/>
        <%= f.label :item_price %><br/>
        <%= f.number_field :item_price, size: 6, step: 0.01, class: ("form-control")  %><br/>
        <%= f.label :end_time %><br/>
        <div class="form-control">
        <span>Date: <%= f.date_select :end_time, class: ("form-control")  %></span>
        <span>Time:<%= f.time_select :end_time, ignore_date: true, :ampm => true,class: ("form-control")  %></span>
        </div>
        <br/><br/>
        <%= f.submit 'New Deal', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/vendors/_deal_manager.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Mangage Deals & Followers:</h3>
  </div>
  <div class="panel-body">
    <h5>Use the operations below to interact with users and post new deals. We give you the choice to manually text and email your users that deals are available but ask that you do so with restraint.</h5>
  </div>
  <table class="table">
    <tr>
      <td><h4>Create a New Deal:</h4></td>
      <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newDeal">New Deal</button></td>
    </tr>
    <tr>
      <td><h4>See Your Followers:</h4></td>
      <td><%= link_to "Followers", followers_path, class: 'btn btn-primary' %></td>
    </tr>
    <tr>
      <td><h4>Connect to Stripe:</h4></td>
      <td><a id="stripebutton"href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=<%=ENV['STRIPE_CLIENT_ID']%>&scope=read_write"><button class="btn btn-primary">Launch Stripe</button></td></a>
    </tr>
    <tr>
      <td><h4>Send Followers a Text:</h4></td>
      <td><%= link_to 'Send Text', text_path, class: 'btn btn-warning' %></td>
    </tr>
    <tr>
      <td><h4>Send Followers an Email:</h4></td>
      <td><%= link_to 'Send Mail', email_path, class: 'btn btn-warning' %></td>
    </tr>
  </table>
</div>
<!-- Modal for new deal -->
<div class="container">
  <div class="modal fade" id="newDeal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">New Deal</h4>
        </div>
        <div class="modal-body">
          <%= render 'deal_form', locals: {deal: @deal} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/vendors/_edit.html.erb
<%= form_for @vendor, method: "put" do |f| %>
  <%= f.label :username, 'Username:' %><br>
  <%= f.text_field :username %><br><br>
  <%= f.label :email, 'Email:' %><br>
  <%= f.text_field :email %><br><br>
  <%= f.label :name, 'Business Name:' %><br>
  <%= f.text_field :name %><br><br>
  <%= f.label :address, 'Address:' %><br>
  <%= f.text_field :address %><br><br>
  <%= f.label :phone_number, 'Phone Number:' %><br/>
  <%= f.text_field :phone_number %><br/><br/>
  <%= f.label :bio, 'Company Bio' %><br/>
  <%= f.text_area :bio, cols:50, rows: 10 %><br/>
  <%= f.label :avatar, 'Profile Picture' %>
  <%= f.file_field :avatar %><br><br>
  <%= f.submit 'Submit', class: 'btn btn-warning' %>
<% end %>
<br>
<%= link_to 'delete account', vendor_path, method: 'delete', data: {confirm: "Are you sure you want to delete your account?"} %>

app/views/vendors/_edit_vendor.html.erb
<div class="container">
  <div class="modal fade" id="vendorEdit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Edit Profile</h4>
        </div>
        <div class="modal-body">
          <%= render partial: 'vendors/edit' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/vendors/_new_deal.html.erb
<div class="container">
  <div class="modal fade" id="newDeal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Modal title</h4>
        </div>
        <div class="modal-body">
          <%= render 'deal_form', locals: {deal: @deal} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/vendors/_profile_pic.html.erb
<% if vendor.avatar.exists? %>
  <%= image_tag vendor.avatar.url(:medium), class: 'img-rounded' %>
<% else %>
  <%= link_to image_tag('profile.png', size: '150x150'), "#pic-upload", :data => { :toggle =>"modal" } %>
  <% if current_vendor %>
    <%= render partial: 'vendors/update_profile_pic' %>
  <% end %>
<% end %>

app/views/vendors/_report.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Reports</h4></div>
  <div class="panel-body">

  <small>Success</small>
  <div class="progress">
    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100" style="width: 72%">
      <span class="sr-only">72% Complete</span>
    </div>
  </div>
  <small>Info</small>
  <div class="progress">
    <div class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
      <span class="sr-only">20% Complete</span>
    </div>
  </div>
  <small>Warning</small>
  <div class="progress">
    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
      <span class="sr-only">60% Complete (warning)</span>
    </div>
  </div>
    <small>Danger</small>
    <div class="progress">
      <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
        <span class="sr-only">80% Complete</span>
      </div>
    </div>
  </div>
</div>

app/views/vendors/_update_profile_pic.html.erb
<div class="modal fade" id="pic-upload" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Upload Profile Picture</h4>
      </div>
      <div class="modal-body">
        <%= form_for @vendor, class: 'text-center', method: "put", :html => { :multipart => true } do |form| %>
          <%= form.file_field :avatar, :default_url => '/assets/images/profile.png' %>
          <%= form.submit class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/vendors/_user.html.erb
<div class="container">
  <div class="row">
    <div id="last-five" class="col-md-3">
      <h1><%= vendor.name %></h1>
      <h5>address:</h5>
      <h6><%= vendor.address %></h6>
      <h5>phone:</h5>
      <h6> <%= vendor.phone_number %></h6>
      <h5>about:</h5>
      <h6><%= vendor.bio %></h6>
    </div>
    <div class="col-md-6 text-center">
      <div class="vendor-map">
        <div id="panel">
          <input type="hidden" id="address" type="textbox" value="<%= @vendor.address %>">
        </div>
        <div id="map-canvas"></div>
      </div>
    </div>
    <div id="considerations" class="col-md-3">
      <h3>Things to Consider When Purchasing:</h3>
      <ul>
        <li>Leave yourself plenty of time to get to the store and pick up your food.</li>
        <li>Contact the vendor who posted the deal with any questions or concerns.</li>
        <li>Ask your vendor if they are open to delivering the good purchased.</li>
        <li>Use solid judgement, don't buy anything you won't be able to pick up or use.</li>
        <li>Read our <a href="#">User terms and conditions</a>.</li>
      </ul>
    </div>
  </div>
</div>

app/views/vendors/_vendor.html.erb
<div class="container">
  <div class="row">
    <div id="last-five" class="col-md-3">
      <h3>Your Last Five Deals:</h3>
      <% @last_five.each do |deal| %>
        <ul>
          <h3><%= link_to deal.title, deal_path(deal.id) %></h3>
        </ul>
      <% end %>
    </div>
    <div class="col-md-6">
        <% unless current_vendor_stripe_link? %>
           <script type="text/javascript">
            $(window).load(function(){
              $('#stripeModal').modal('show');
            });
          </script>
        <% end %>
      <%= render 'deal_manager', locals: {deal: @deal} %>
    </div>
    <div id="considerations" class="col-md-3">
      <h3>Things to Consider While Posting:</h3>
      <ul>
        <li>Consider grouping items together into a single deal and selling items in bulk groups.</li>
        <li>Post items with enough time left on them to allow for your customers to pick up.</li>
        <li>Put a reasonable price on the item to sell it quickly. Remember, you were going to throw it away!</li>
        <li>Post a day in advance if you know that those items will go bad or not be purchased.</li>
      </ul>
    </div>
  </div>
</div>

<!-- Modal for Stripe Sign Up -->
<div class="container">
  <div class="modal fade" id="stripeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title text-center" id="myModalLabel">Sign up with Stripe!</h4>
        </div>
        <div class="modal-body">
          <div id="stripebuttondiv">
            <h1>You need to link or create your Stripe account!</h1>
            <p>Follow the link below</p>
            <a id="stripebutton"href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=<%=ENV['STRIPE_CLIENT_ID']%>&scope=read_write"><button class="btn btn-primary">Create or Link Stripe</button>
            <p></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/vendors/edit.html.erb
<h1>Vendor Edit Page</h1>
<%= form_for @vendor, method: "put" do |f| %>
  <%= f.label :username, 'Username:' %><br>
  <%= f.text_field :username %><br><br>
  <%= f.label :email, 'Email:' %><br>
  <%= f.text_field :email %><br><br>
  <%= f.label :name, 'Business Name:' %><br>
  <%= f.text_field :name %><br><br>
  <%= f.label :address, 'Address:' %><br>
  <%= f.text_field :address %><br><br>
  <%= f.label :phone_number, 'Phone Number:' %><br/>
  <%= f.text_field :phone_number %><br/><br/>
  <%= f.label :bio, 'Company Bio' %><br/>
  <%= f.text_area :bio, cols:50, rows: 10 %><br><br>
  <%= f.submit 'Sign Up!', class: 'btn btn-warning' %>
<% end %>
<%= link_to 'destroy vendor', vendor_path, method: 'delete' %>

app/views/vendors/followers.html.erb
<%= render partial: '/vendors/followers', locals: {followers: @vendor.users} %>

app/views/vendors/index.html.erb
<h1>Vendors</h1>

<% @vendors.each do |vendor| %>
  <%=render partial: '/vendors/showvendor', locals: {vendor: vendor} %>
<% end %>

app/views/vendors/show.html.erb
<div class="container">
  <div id="profile-top-bar" class="row">

    <div class="col-md-4">
      <h1 id="welcome-user">Hello!</h1>
    </div>

    <div class="col-md-4">
      <ul>
        <h3>Current Deals:</h3>
      </ul>
      <% @current_deals.each do |deal| %>
        <ul>
          <h3><%= link_to deal.title, deal_path(deal) %></h3>
        </ul>
      <% end %>
    </div>

    <div class="col-md-4 text-center">

      <%= render partial: 'vendors/profile_pic', locals: {vendor: @vendor} %>

      <hr>
      <h3>Username: <%= @vendor.name %></h3>
      <h4>Phone: <%= @vendor.phone_number %></h4>
      <h4>Email: <%= @vendor.email %></h4>
      <h4>Followers: <span class="badge"><%= @vendor.favorite_vendors.count %></span></h4>
      <% if current_vendor %>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#vendorEdit">Edit Profile</button>
        <%= render partial: 'vendors/edit_vendor' %>
      <% end %>
    </div>
  </div>
</div>
<% if current_vendors_page?(@vendor) %>
  <%=render partial: '/vendors/vendor', locals: {vendor: @vendor, current_deals: @current_deals, last_five: @last_five, deal: @deal} %>
<% else %>
  <%=render partial: '/vendors/user', locals: {vendor: @vendor, current_deals: @current_deals} %>
<% end %>

<!-- renders modal for login (user & vendor) -->
<%= render 'welcome/vendor_login', locals: {@user => @user, @vendor => @vendor}%>
<%= render 'welcome/user_login', locals: {@user => @user, @vendor => @vendor}%>
<!-- renders modal for vendor sign up -->
<%= render 'welcome/signup_vendor', locals: {@vendor => @vendor} %>
<%= render 'user/new_user', locals: {@user => @user, @vendor => @vendor}%>