config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/about' => 'welcome#about', as: 'about'
  get '/vendors/:id/followers' => 'vendors#followers', as: 'followers'
  resources :sessions, only: [:new]

  get '/login' => 'sessions#new'
  post '/login_user' => 'sessions#user_create'

  get '/login' => 'sessions#new'
  post '/login_vendor' => 'sessions#vendor_create'
  delete '/logout' => 'sessions#destroy'

  resources :vendors
  resources :deals do
    resources :purchased_items, only: [:new, :create]
  end
  resources :user
  get 'stripe', to: 'vendors#stripe_acct'

  get '/vendors/:id/text' => 'vendors#send_sms', as: 'text'
  get '/vendors/:id/email' => 'vendors#email_followers', as: 'email'
  put '/vendors/:id/follow' => 'vendors#follow', as: 'follow'
  delete '/vendors/:id/unfollow' => 'vendors#unfollow', as: 'unfollow'
  get '/vendor_session/new' => 'sessions#new_vendor_session', as: 'new_vendor_session'

  resources :charges
end

app/views/layouts/_nav.html.erb
<nav id="nav-top" class="collapse navbar-collapse" role="banner">
  <a href="/" class="navbar-brand">Full-Bellies</a>
  <% if session[:user_id] || session[:vendor_id] %>
    <ul id="nav-top" class="nav navbar-nav">
      <li><%= link_to 'Logout', logout_path, method: 'delete' %></li>
    </ul>
    <% if session[:vendor_id] %>
      <ul id="nav-top" class="nav navbar-nav navbar-right">
        <li><%= link_to 'Vendor Profile', vendor_path(session[:vendor_id]) %></li>
      </ul>
    <% else %>
      <ul id="nav-top" class="nav navbar-nav navbar-right">
        <li><%= link_to 'Profile Page', user_path(session[:user_id]) %></li>
      </ul>
    <% end %>
  <% else %>
    <ul id="nav-top" class="nav navbar-nav pull-right">
      <li data-toggle="modal" data-target="#vendorModal"><a href="#">Login</a></li>
      <li data-toggle="modal" data-target="#vendorSignup"> <a href="#">Are you a business?</a></li>
      <li data-toggle="modal" data-target="#signup"><a href="#">Signup</a></li>

    </ul>
  <% end %>
  <ul id="nav-top" class="nav navbar-nav">
    <li><%= link_to 'Deals', deals_path %></li>
    <li><%= link_to 'Mission', about_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FullBellies</title>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places" %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
  <% end %>
  <%= render partial: 'layouts/nav' %>
  <%= yield %>
  <div class="container">
    <footer><hr>
      <p class="pull-right"><a href="#">Back to top</a></p>
      <p>&copy; 2015 Full-Bellies, Inc. &middot; <a href="#">Terms</a> &middot; <a href="#">Contact</a></p>
    </footer><hr>
  </div>
</body>
</html>